name: Fantasy Median Bot

on:
  schedule:
    # Sundays every hour from 1PM–11PM EST
    - cron: '0 18-23 * * 0'   # 1PM–6PM EST is 18–23 UTC
    - cron: '0 0-3 * * 1'     # 7PM–11PM EST is 0–3 UTC (Monday UTC, but still Sunday EST)

    # Mondays every hour from 9PM–11PM EST
    - cron: '0 1-3 * * 2'     # 9PM–11PM EST = 1–3 UTC on Tuesday

  workflow_dispatch:  # allow manual trigger from GitHub UI

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          LEAGUE_ID: ${{ secrets.LEAGUE_ID }}
          SWID: ${{ secrets.SWID }}
          ESPN_S2: ${{ secrets.ESPN_S2 }}
          GROUPME_BOT_ID: ${{ secrets.GROUPME_BOT_ID }}
        run: |
          python bot.py
