name: Fantasy Median Bot

on:
  schedule:
    # Sundays every hour from 1PM–11PM EST
    - cron: '0 18-23 * * 0'
    - cron: '0 0-3 * * 1'
    # Mondays every hour from 9PM–11PM EST
    - cron: '0 1-3 * * 2'
  workflow_dispatch:  # manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          LEAGUE_ID: "2075760555"
          YEAR: "2025"
          SWID: "{AFDF1C35-C3FF-4E8F-AD85-63D85CCE88ED}"
          ESPN_S2: "AECFFuqpnKkwgOlcCijqY71viRNLKIOsWVRu4cRQKbzfnIrJbf0jkAZ9x3csHAQz03U0D%2F9oCeXuchZVZa0M6Z4VQSYiFUwr7%2F5rrE1LZ6O6ySVeWsLC7xTsx%2FlDvw83DfRsffDlAaNdichxwCO2SY274IL0Cmlq68Ght9P8cekf4qid20hElhBWHC4KXdzVfPrh%2BX9tZIKqfxmtBtgC4Qf4m%2BueKsogUnTADTF672fbxy8G3LcurbepB1YLOehRokBXx9alTK3qS6b19hFlMOI5ch%2Bzaax2GIbYiitGkYDYXb%2B1Iatss9pwd1aSkt87XyI%3D"
          GROUPME_BOT_ID: "b63cecb7e82d210797808b6f11"
          TEST_MODE: "false"
        run: |
          python bot.py
