name: Fantasy Median Bot

on:
  schedule:
    # Run every minute
    - cron: "*/1 * * * *"
  workflow_dispatch:  # allow manual trigger too

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests pytz espn-api

      - name: Run bot
        env:
          GROUPME_BOT_ID = "b63cecb7e82d210797808b6f11"
          ESPN_S2: "AECFFuqpnKkwgOlcCijqY71viRNLKIOsWVRu4cRQKbzfnIrJbf0jkAZ9x3csHAQz03U0D%2F9oCeXuchZVZa0M6Z4VQSYiFUwr7%2F5rrE1LZ6O6ySVeWsLC7xTsx%2FlDvw83DfRsffDlAaNdichxwCO2SY274IL0Cmlq68Ght9P8cekf4qid20hElhBWHC4KXdzVfPrh%2BX9tZIKqfxmtBtgC4Qf4m%2BueKsogUnTADTF672fbxy8G3LcurbepB1YLOehRokBXx9alTK3qS6b19hFlMOI5ch%2Bzaax2GIbYiitGkYDYXb%2B1Iatss9pwd1aSkt87XyI%3D"
          SWID: "{AFDF1C35-C3FF-4E8F-AD85-63D85CCE88ED}"
        run: |
          python playoff_odds_bot.py
