name: Fantasy Median Bot

on:
  schedule:
    # Sundays 4PM–11:59PM EST (21–23 UTC, plus 0–4 UTC Monday)
    - cron: "*/5 21-23 * * 0"   # Sun 4–6PM EST
    - cron: "*/5 0-4 * * 1"     # Sun 7–11PM EST, early Mon UTC

    # Mondays 9:30PM–11:59PM EST (Tues 2–5 UTC)
    - cron: "*/5 2-5 * * 2"

    # Thursdays 11:59PM EST (Fri 4 UTC)
    - cron: "*/5 4 * * 5"
  workflow_dispatch:  # manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        run: |
          python bot.py
