name: Fantasy Median Bot

on:
  schedule:
    # Run every minute
    - cron: "*/1 * * * *"
  workflow_dispatch:  # allow manual trigger too

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests pytz espn-api

      - name: Run bot
        env:
          GROUPME_BOT_ID: ${{ secrets.GROUPME_BOT_ID }}
          ESPN_S2: ${{ secrets.ESPN_S2 }}
          SWID: ${{ secrets.SWID }}
        run: |
          python playoff_odds_bot.py
